force-app/main/default/objects/Cash_Flow__c/Cash_Flow__c.object-meta.xml
<CustomObject>
    <label>Cash Flow</label>
    <nameField>
        <displayFormat>CF-{0000}</displayFormat>
        <label>Cash Flow Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cash Flows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cash_Flow__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Amount</label>
    <precision>12</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Working_Capital__c.field-meta.xml
<CustomField>
    <fullName>Working_Capital__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Working Capital</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/CashFlowTriggerHandler.cls
public with sharing class CashFlowTriggerHandler {

    public static void updateWorkingCapitalOnInsert(List<Cash_Flow__c> newCashFlowObjs){

        final String CAPTIAL_RECORD_TYPE = '012P00000032nUTIAY';
        final String EXPENSE_RECORD_TYPE = '012P00000032nUYIAY';

        final String USER_ID = UserInfo.getUserId();  // built in function to get current logged in user id.

        User currentUserObj = [SELECT UserName, Working_Capital__c, Email FROM User WHERE Id = :USER_ID];

        for(Cash_Flow__c cf : newCashFlowObjs) {
            if(cf.RecordTypeId == CAPTIAL_RECORD_TYPE) {
                currentUserObj.Working_Capital__c = currentUserObj.Working_Capital__c == null 
                    ? cf.Amount__c 
                    : currentUserObj.Working_Capital__c + cf.Amount__c;  
            } 
            // use another if statement instead of else so if there is additional record
            // type in the future, less code change / logic change.
            if(cf.RecordTypeId == EXPENSE_RECORD_TYPE) {
                currentUserObj.Working_Capital__c = currentUserObj.Working_Capital__c == null 
                    ? cf.Amount__c 
                    : currentUserObj.Working_Capital__c - cf.Amount__c;  
                
            }
        }

        update currentUserObj;
    }
}